<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-BLLEEJVQ" name="testcases.S20_10_ArchitectCertifications_POM" tests="1" failures="0" timestamp="2021-02-26T23:18:58 IST" time="35.063" errors="1">
  <testcase name="verifyArchitectCertifications" time="35.063" classname="testcases.S20_10_ArchitectCertifications_POM">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at pages.CustomerServicePage.<init>(CustomerServicePage.java:22)
at pages.HomePage.clickLearnMore(HomePage.java:56)
at testcases.S20_10_ArchitectCertifications_POM.verifyArchitectCertifications(S20_10_ArchitectCertifications_POM.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- verifyArchitectCertifications -->
  <system-out/>
</testsuite> <!-- testcases.S20_10_ArchitectCertifications_POM -->
